ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [
    path('addtocart/<int:p>/',views.addtocart,name="addtocart"),
    path('cart_view/',views.cart_view,name="cart_view"),
    path('cart_remove/<int:p>/',views.cart_remove,name="cart_remove"),
    path('fullremove/<int:p>/',views.full_remove,name="full_remove"),
    path('orderform/',views.orderform,name="orderform"),
    path('yourorder/',views.yourorders,name="yourorder")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [
    path('search/',views.searchproducts,name="searchpro"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('products/<int:p>',views.allproducts,name='allpro'),
    path('details/<int:p>',views.showdetails,name='details'),
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import product
from django.contrib.auth.models import User

class cart(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class order_table(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    phone=models.IntegerField()
    address=models.TextField()
    ordered_date=models.DateTimeField(auto_now_add=True)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")

    def __str__(self):
        return self.user.username

class account(models.Model):
    acctnum=models.BigIntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to='media/image',blank=True,null=True)

    def __str__(self):
        return self.name

class product(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to='products', blank=True, null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True) #one time
    updated=models.DateTimeField(auto_now=True) #every time we update records
    category=models.ForeignKey(category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import product
from cart.models import cart,order_table,account
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

@login_required
def cart_view(request):
    u=request.user
    total=0
    c=cart.objects.filter(user=u)
    for i in c:
        total=total+i.quantity*i.product.price

    return render(request,'cart.html',{'c':c,'total':total})

@login_required

def addtocart(request,p):
    p=product.objects.get(id=p)
    u=request.user
    try:
        Cart=cart.objects.get(user=u,product=p)
        if(p.stock>0):
            Cart.quantity+=1
            Cart.save()
            p.stock-=1
            p.save()
    except:

        Cart=cart.objects.create(product=p,user=u,quantity=1)
        Cart.save()
        p.stock-=1
        p.save()
    return cart_view(request)
@login_required

def cart_remove(request,p):
    p=product.objects.get(id=p)
    u=request.user
    try:
        Cart=cart.objects.get(user=u,product=p)
        if (Cart.quantity>1):
            Cart.quantity-=1
            Cart.save()
            p.stock+=1
            p.save()
        else:
            Cart.delete()
            p.stock+=1
            p.save()

    except:
        pass
    return cart_view(request)


def full_remove(request,p):
    p=product.objects.get(id=p)
    u=request.user
    try:
        Cart=cart.objects.get(user=u,product=p)
        Cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
        pass 
    return cart_view(request)

@login_required
def orderform(request):
    if (request.method=="POST"):
        a=request.POST['a']
        p = request.POST['p']
        an = request.POST['n']
        u=request.user
        c=cart.objects.filter(user=u)
        total=0
        for i in c:
            total=total+i.quantity*i.product.price

        try:
            ac=account.objects.get(acctnum=an)
            if(ac.amount >= total):
                ac.amount=ac.amount-total
                ac.save()
                for i in c:
                    o=order_table.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()

                c.delete()
                msg="Order Placed Sucessfully"

                return render(request,'orderdetail.html',{'message':msg})
            else:
                msg="Insufficient Amount.You Cant Place Order"
                return render(request,'orderdetail.html',{'message':msg})
        except:
            pass
    return render(request,'orderform.html')

@login_required
def yourorders(request):
    u=request.user
    s=order_table.objects.filter(user=u)
    return render(request,'yourorders.html',{'s':s})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q


# Create your views here.
def searchproducts(request):
    p=None
    query=""
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            p=product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))


    return render(request,'search.html', {'p':p,'q':query})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from shop.models import category,product
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout

def allcategories(request):
    c=category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=category.objects.get(id=p)# retrievs a particular category
    p=product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def showdetails(request,p):
    p=product.objects.get(id=p)
    return render(request,'details.html',{'p':p})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']

        if(cp==p):
            user=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            user.save()
            return allcategories(request)
        else:
            return HttpResponse("passwords are not same")
    return render(request, 'register.html')
def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return allcategories(request)
        else:
            return HttpResponse("invalid credentials")

    return render(request,'login.html')

def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Graduate&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-light"><img src="{% static 'images/logo1.png' %}" height="60px" width="60px" >
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><b>MyShop</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All-Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allpro' i.id %}">{{i.name}}</a></li>

               <li class="nav-item">

               {% endfor %}



          </ul>
        </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser != True %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cart_view' %}"><i class="fa-solid fa-cart-shopping" style="font-size:25px;"><sup style="color:red;">{{count}}</sup></i></a>
        </li>
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:yourorder' %}">Your Orders</a>
        </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>

          {% endif %}

      </ul>

      <form class="d-flex" method="POST" action="{% url 'search:searchpro' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-info me-5" type="submit">Search</button>


      </form>
    </div>
  </div>
</nav>

{% block content %}


{% endblock %}


<footer id="footer" class="mt-5">

     <h6><img src="{% static 'images/logo1.png' %}" height="60px" width="60px">MYSHOP</h6>

    <center><h6><i class="fa-solid fa-copyright"></i>MyShop private ltd.All rights reserved</h6></center>

    <p></p>

</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<br>


<div class="container-fluid mt-5" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center text-dark">Shoping Cart</h4>

        <div class="col-7">

            <table class="table table-bordered border-dark">
                <tr>
                    <th colspan="6">Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                    <td><b>{{i.product.name}}</b></td>
                    <td><b>Product id:{{i.product.id}}</b>
                    Quantity:{{i.quantity}}<br>
                    unit price:{{i.quantity}}*{{i.product.price}}</td>
                    <td>Sub-Total:<h5><b>{{i.subtotal}}</b></h5></td>
                    <td>

                        {% if i.product.stock > 0 %}
                        <br><a href="{% url 'cart:addtocart' i.product.id %}"  %><i class="fa-solid fa-circle-plus h6" style="color:black;"></i></a>
                        <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus h6" style="color:black;"></i></a><br>
                        <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash-can h6" style="color:black;"></i></a>
                        {% else %}
                        <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus h6" style="color:black;"></i></a><br>
                        <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash-can h6" style="color:black;"></i></a>
                        {% endif %}

                        </td>
                </tr>
                {% endfor %}
            </table>

        </div>

        <div class="col-4" style="position:relative">

             <table class="table table-bordered border-dark">
                <tr>
                    <th colspan="6">Check Out</th>
                </tr>
                 <tr>
                     <td colspan="4">TOTAL AMOUNT:₹{{total}}</td>
                 </tr>
             </table>
            <a class="btn btn-info" href="{% url 'cart:orderform' %}">Place Order</a>
            <a class="btn btn-info" href="{% url 'shop:allcat' %}">Continue..</a>

        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<div style="margin-bottom:20px;" >
     <img src="{% static 'images/banr.jpg' %}" height="550px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px">
     <h3 class="text-center fw-bold">OUR COLLECTIONS</h3>
     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<div class="container-fluid" style="margin-bottom:100px">
     <div class="row">
          {% for i in c %}
          <div class="col-sm-3">
               <div class="card" style="width: 18rem;">
                    <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:12rem;">
               <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>

                    <a href="{% url 'shop:allpro' i.id %}" class="btn btn-info">Shop Now</a>
               </div>
               </div>
          </div>
          {% endfor %}
     </div>
</div>
<div style="margin-bottom:20px;" >
     <img src="{% static 'images/close-up-woman-shouting-via-loudspeaker.jpg' %}" height="550px" width="100%">
</div>



{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="row">
        <div class="col-md-6" style="margin-top:100px;">
            <img src="{{p.image.url}}" height="400px;" width="100%;">
        </div>
        <div class="col-md-6 fw-bold" style="margin-top:100px;">
            <h2>{{p.name}}</h2>
            <br>
            <br>
            <h6>{{p.desc}}</h6>
            <h5>Price: ₹{{p.price}}</h5>
            <h6>Available Stocks:{{p.stock}}</h6>
            <br>
            {% if user.is_superuser == True %}

                 {% if p.stock > 0 %}
                     <h3 class="text-info">Product In Stock</h3>
                     <a href="{% url 'admin:index' %}" class="btn btn-info">Add Stock</a>
                 {% else %}
                     <h3 class="text-danger">Product Out Of Stock</h3>
                     <a href="{% url 'admin:index' %}" class="btn btn-info">Add Stock</a>
                 {% endif %}

            {% else %}
                 {% if p.stock > 0 %}
                      <a href="{% url 'cart:addtocart' p.id %}" class="btn btn-info">Add to Cart</a>
                 {% else %}
                      <h3 class="text-danger">Product Out Of Stock</h3>

                  {% endif %}

            {% endif %}
        </div>
    </div>

{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}login{% endblock %}
{% block content %}
<br>
<br>
<br>


<center><h1>Login</h1></center>
<br>
<br>

<!--<body style="background-image:url('{% static "images/boook.jpg" %}');background-size:cover;">-->
<center><form method="POST" style="width:500px;">
    {% csrf_token %}

    <div class="mb-3">
      <label class="form-label">username</label>
      <input type="text"  class="form-control" name="u" placeholder="Enter your username here">
    </div>
       <div class="mb-3">
      <label  class="form-label">password</label>
      <input type="password"  class="form-control" name="p" placeholder="Enter your password">
    </div>
    <br>
    <br>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>
    </center>
<br>
<br>
<br>
<br>

{% endblock %}

</body>
</html>

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% block content %}
<br><br><br><br><br><br><br><br><br><br><br><br>
<div class="container">
<!--    <i class="fa-regular fa-circle-check text-center"></i>-->
    <h3 class="text-center text-info">{{message}}</h3>
    <h4 class="text-center text-warning">Thank You..</h4>
    <h5 class="text-center"><a href="{% url 'shop:allcat' %}" class="btn btn-danger">Continue Shopping</a></h5>

</div>


<br><br><br><br><br><br><br><br>

{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<center><form method="POST" style="width:500px;">
    {% csrf_token %}

    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text"  class="form-control" name="a" placeholder="Enter your address here">
    </div>
       <div class="mb-3">
      <label  class="form-label">Phone</label>
      <input type="text"  class="form-control" name="p" placeholder="Enter your Phone number">
    </div>
     <div class="mb-3">
      <label  class="form-label">Ac Number</label>
      <input type="text"  class="form-control" name="n" placeholder="Enter your Account Number">
    </div>
    <br>
    <br>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>
    </center>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<div style="margin-bottom:20px;" >
     <img src="{{c.image.url}}" height="550px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px">
     <h3 class="text-center fw-bold">OUR COLLECTIONS</h3>
     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<div class="container-fluid" style="margin-bottom:100px">
     <div class="row">
          {% for i in p %}
          <div class="col-sm-3">
               <div class="card" style="width: 18rem;">
                    <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:12rem;">
               <div class="card-body">
                    <h6 class="card-title">{{i.name}}</h6>
                    <h4>₹{{i.price}}</h4>
                    <a href="{% url 'shop:details' i.id %}" class="btn btn-info">Shop Now</a>
               </div>
               </div>
          </div>
          {% endfor %}
     </div>
</div>



{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}register{% endblock %}
{% block content %}
<br>
<br>
<br>

<center><h1>Register Here..</h1></center>
<br>
<body>
<center>
<form method="POST" style="width:500px;">
    {% csrf_token %}

    <div class="mb-3">
      <label class="form-label">username</label>
      <input type="text"  class="form-control" name="u" placeholder="Enter your username here">
    </div>
       <div class="mb-3">
      <label  class="form-label">password</label>
      <input type="password"  class="form-control" name="p" placeholder="Enter your password">
    </div>
       <div class="mb-3">
      <label  class="form-label">Confirm Password</label>
      <input type="password"  class="form-control" name="cp" placeholder="Confirm your password">
    </div>
       <div class="mb-3">
      <label  class="form-label">Email</label>
      <input type="email"  class="form-control" name="e" placeholder="Enter your email">
    </div>
       <div class="mb-3">
      <label  class="form-label">first_name</label>
      <input type="text"  class="form-control" name="f" placeholder="Enter your first name">
    </div>
        <div class="mb-3">
      <label  class="form-label">last_name</label>
      <input type="text"  class="form-control" name="l" placeholder="Enter your last name">
    </div>
    <br>
    <br>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>
    </center>



</body>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container-fluid" style="margin-bottom:100px">
     {% if p %}
     <div class="row">
          {% for i in p %}
          <div class="col-sm-3">
               <div class="card" style="width: 18rem;">
                    <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:12rem;">
               <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <h3>₹{{i.price}}</h3>
                    <a href="{% url 'shop:details' i.id %}" class="btn btn-info">Shop Now</a>
               </div>
               </div>
          </div>
          {% endfor %}
     </div>
     {% else %}
     <center><h4 style="margin-top:200px;margin-bottom:200px;"><b>No search found</b></h4></center>

</div>
{% endif %}


{% endblock %}

ecommerce/templates/yourorders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br>
<div class="row">
    {% for i in s %}
    <h2> customer name:{{i.user}}</h2>

<div class="col-md-6">
    <img src="{{i.product.image.url}}" height="400px;"width="100%;">
</div>
        <div class="col-md-6">
            <h1>{{i.product}}</h1>
            <p>{{i.product.price}}</p>
            <P>Delivery_address:{{i.address}}</p>
           <P>Phone Number:{{i.phone}}</p>
            <P>No_of_items:{{i.no_of_items}}</p>
            <P>Orderd_On:{{i.ordered_date}}</p>
            <P>Delivery_Status:{{i.delivery_status}}</p>
        </div>
    {% endfor %}
</div>
<br><br><br><br><br><br><br><br><br><br>
{% endblock %}